### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by APIQuality-io**
Add APIQuality to Microcks adopters

### Description

- ...
- ...
- ...

### CODE REVIEW

**Comment by yada** [comment]
Thanks, @APIQuality-io, for this PR, but you are already listed:

API Quality | Omar del Valle | We are using Microcks for a step of the API first cycle.
-- | -- | --

Can you update and create a single entry?

**Comment by yada** [comment]
Hi @APIQuality-io,

The new entry is ok, but could you please delete the old line in your PR:
"
API Quality | Omar del Valle | We are using Microcks for a step of the API first cycle.
-- | -- | --


[API Quality](https://apiquality.io/en/)	[Omar del Valle](https://www.linkedin.com/in/omardelvalle/)	We are using Microcks for a step of the API first cycle."

So, I merge the update.
Thank you

**Comment by APIQuality-io** [comment]
Hi again! sorry, we didn't see this comment. Could you explain us how to remove that line? We just need to delete it from de ADOPTERS.md?

Thanks!

**Comment by APIQuality-io** [comment]
We just did it: we removed the previous line, but we don't see the new information that we added before.

**Review by yada — APPROVED** [review]
LGTM

**Comment by yada** [comment]
The merge has been completed, and I have removed the previous entry for you (See https://github.com/microcks/.github/commit/3baaa1593000c2b1b9c4a9c879cd5b29156e1675). It's all done now, with thanks.

**Pull request merged**
