### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by Damounet**
Add Inetum Software use case as Microck adopter

### Description

- ...
- ...
- ...

### CODE REVIEW

**Comment by yada** [comment]
Thank you very much @Damounet, for this PR and for joining Microcks' adopters list. It is appreciated.
May I suggest these modifications for the description:
>We use Microcks as an API centralisation and mock server for the social and civil security division, paving the path for migration to microservices and event-driven cloud architecture.

Can you update it, if it is OK with you?

**Comment by yada** [comment]
LGTM with thanks 
Can you sign the PR (see DCO check), and I will be happy to merge right after ;-)

**Comment by Damounet** [comment]
Finaly got the time to have a look into this DCO thing. sorry for the wait.

**Comment by yada** [comment]
Merged with thanks @Damounet 🙌

**Pull request merged**
